.TH suse-public-cloud-plugin "8" "04 Feb 2016" "suse-public-cloud-plugin" "Support Utilities Manual"
.SH NAME
suse-public-cloud-plugin \- SUSE Public CloudPlugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This
plugin extends supportconfig's functionality to include pertinent information
for instances running in the Public Cloud launched from SUSE published images.
Supportconfig saves the plugin output in the public_cloud subdirectory.

.SH FILES
.I /usr/lib/supportconfig/plugins/suse_public_cloud
.RS

The SUSE Public Cloud plugin for supportutils
.RE
.SH AUTHOR
Robert Schweikert <rjschwei@suse.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://bugzilla.suse.com
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
