#!/usr/bin/python

# Copyright 2015 SUSE LLC, Robert Schweikert
#
# This file is part of ec2uploadimg.
#
# ec2uploadimg is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ec2uploadimg is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ec2uploadimg. If not, see <http://www.gnu.org/licenses/>.

import ConfigParser
import argparse
import boto
import boto.ec2
import os
import sys

import ec2utils.ec2utilsutils as utils
import ec2utils.ec2uploadimg as ec2upimg
from ec2utils.ec2UtilsExceptions import *

# Check the boto API version before doing anything
apiVersion = boto.__version__
major, minor, release = apiVersion.split('.')
if int(major) < 2 or int(minor) < 22:
    print 'Need to use boto version 2.22.0 or higher. Installed version: ',
    print apiVer
    sys.exit(1)

# Set up command line argument parsing
argparse = argparse.ArgumentParser(description='Upload image to Amazon EC2')
argparse.add_argument(
    '-a', '--account',
    dest='accountName',
    help='Account to use (Optional)',
    metavar='ACCOUNT_NAME'
)
argparse.add_argument(
    '--access-id',
    dest='accessKey',
    help='AWS access key (Optional)',
    metavar='AWS_ACCESS_KEY'
)
argparse.add_argument(
    '-B', '--backing-store',
    default='ssd',
    dest='backingStore',
    help='The backing store type, (mag|ssd) (Optional)',
    metavar='EC2_BACKING_STORE'
)
argparse.add_argument(
    '--boot-kernel',
    dest='akiID',
    help='AWS kernel ID (aki) to boot the new image (Optional)',
    metavar='AWS_AKI_ID'
)
argparse.add_argument(
    '-d', '--description',
    dest='descript',
    help='Image description, will also be used for the snapshot',
    metavar='IMAGE_DESCRIPTION',
    required=True
)
argparse.add_argument(
    '-e', '--ec2-ami',
    dest='amiID',
    help='AWS AMI id for the image to use to upload (Optional)',
    metavar='AWS_AMI_ID',
)
argparse.add_argument(
    '-f', '--file',
    default=os.path.expanduser('~') + os.sep + '.ec2utils.conf',
    dest='configFilePath',
    help='Path to configuration file, default ~/.ec2utils.conf (Optional)',
    metavar='CONFIG_FILE'
)
argparse.add_argument(
    '--grub2',
    action='store_true',
    default=False,
    dest='grub2',
)
argparse.add_argument(
    '-m', '--machine',
    dest='arch',
    help='Machine architecture i386|x86_64 for the uploaded image',
    metavar='ARCH',
    required=True
)
argparse.add_argument(
    '-n', '--name',
    dest='imgName',
    help='Image name',
    metavar='IMAGE_NAME',
    required=True
)
argparse.add_argument(
    '-p', '--private-key-file',
    dest='privateKey',
    help='Private SSH key file (Optional)',
    metavar='PRIVATE_KEY'
)
argparse.add_argument(
    '-r', '--regions',
    dest='regions',
    help='Comma separated list of regions to upload to (Required)',
    metavar='EC2_REGIONS',
    required=True
)
argparse.add_argument(
    '--ssh-key-pair',
    dest='sshName',
    help='AWS SSH key pair name (Optional)',
    metavar='AWS_KEY_PAIR_NAME'
)
argparse.add_argument(
    '-s', '--secret-key',
    dest='secretKey',
    help='AWS secret access key (Optional)',
    metavar='AWS_SECRET_KEY'
)
argparse.add_argument(
    '--snaponly',
    action='store_true',
    default=False,
    dest='snapOnly',
)
argparse.add_argument(
    'source',
    help='The path to the image source file'
)
argparse.add_argument(
    '-T', '--timeout',
    default=300,
    dest='timeout',
    help='Timeout value to wait for AWS operations, default 300 s (Optional)',
    metavar='WAIT_TIME'
)
argparse.add_argument(
    '-t', '--type',
    dest='instType',
    help='Instance type to use to upload image (Optional)',
    metavar='AWS_UPLOAD_INST_TYPE'
)
argparse.add_argument(
    '-u', '--user',
    dest='sshUser',
    help='The user for the ssh connection to the instance (Optional)',
    metavar='AWS_INSTANCE_USER'
)
argparse.add_argument(
    '-V', '--virt-type',
    default='para',
    dest='virtType',
    help='The virtualization type, (para)virtual or (hvm)',
    metavar='AWS_VIRT_TYPE'
)
argparse.add_argument(
    '--verbose',
    action='store_true',
    default=False,
    dest='verbose',
    help='Enable verbose output'
)

args = argparse.parse_args()
configFile = args.configFilePath
config = None
if not os.path.isfile(configFile):
    print 'Configuration file "%s" not found.' % configFile
    sys.exit(1)
try:
    config = utils.get_config(configFile)
except Exception as e:
    print e.value
    sys.exit(1)

try:
    utils.check_ssh_present(config, args)
except Exception as e:
    print e.value
    sys.exit(1)

try:
    utils.check_account_keys(config, args)
except Exception as e:
    print e.value
    sys.exit(1)

access_key = args.accessKey
if not access_key:
    access_key = utils.get_from_config(args.account,
                                       config,
                                       None,
                                       'access_key_id')

secret_key = args.secretKey
if not secret_key:
    secret_key = utils.get_from_config(args.account,
                                       config,
                                       None,
                                       'secret_access_key')
try:
    for region in regions:
        ami_id = args.amiID
        if not ami_id:
            ami_id = utils.get_from_config(args.account,
                                           config,
                                           region,
                                           'ami')
        bootkernel = args.akiID
        if not bootkernel:
            if args.grub2:
                bootkernel = utils.get_from_config(args.account,
                                                   config,
                                                   region,
                                                   'g2_aki_x86_64')
            elif args.arch == 'x86_64':
                bootkernel = utils.get_from_config(args.account,
                                                   config,
                                                   region,
                                                   'aki_x86_64')
            elif args.arch == 'i386':
                bootkernel = utils.get_from_config(args.account,
                                                   config,
                                                   region,
                                                   'aki_i386')
            elif args.virtType == 'hvm':
                bootkernel = None
            else:
                print 'Could not reliable determine the bootkernel to use '
                print 'must specify bootkernel, arch (x86_64|i386) or hvm'
                sys.exit(1)

        inst_type = args.instType
        if not inst_type:
            inst_type = utils.get_from_config(args.account,
                                              config,
                                              region,
                                              'instance_type')

        key_pair_name = args.sshName
        if not key_pair_name:
            key_pair_name = utils.get_from_config(args.account,
                                                  config,
                                                  region,
                                                  'ssk_key_name')
        ssh_private_key_file = args.privateKey
        if not ssh_private_key_file:
            ssh_private_key_file = utils.get_from_config(args.account,
                                                         config,
                                                         region,
                                                         'ssh_private_key')
        ssh_user = args.sshUser
        if not ssh_user:
            ssh_user = utils.get_from_config(args.account,
                                             config,
                                             region,
                                             'user')

        uploader = ec2upimg.EC2ImageUploader(
                          access_key=access_key,
                          backing_store=args.backingStore,
                          bootkernel=bootkernel,
                          image_arch=args.arch,
                          image_description=args.descript,
                          image_name=args.imgName,
                          image_virt_type=args.virtType,
                          inst_user_name=ssh_user,
                          launch_ami=ami_id,
                          launch_inst_type=inst_type,
                          operation_timeout=args.timeout,
                          secret_key=secret_key,
                          ssh_key_pair_name=key_pair_name,
                          ssh_key_private_key_file=ssh_private_key_file,
                          use_grub2=args.grub2,
                          verbose=args.verbose)

        uploader.set_region(region)
        if args.snapshotOnly:
            snapshot = uploader.create_snapshot(source)
            print 'Created snapshot: ', snapshot.id
        else:
            ami = uploader.create_image(source)
            print 'Created image: ', ami.id
except EC2UploadImgException, e:
    print >> sys.stderr, e
    sys.exit(1)
