#! /bin/sh
# Copyright 2013 SUSE LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
### BEGIN INIT INFO
# Provides:          guestregister
# Required-Start:    $local-fs $network
# Required-Stop:     $null
# Default-Start:     2 3 5
# Default-Stop:
# Short-Description: Get SMT info and "register" with the server
### END INIT INFO

# Return values acc. to LSB for all commands but status:
# 0 - success
# 1 - generic or unspecified error
# 2 - invalid or excess argument(s)
# 3 - unimplemented feature (e.g. "reload")
# 4 - insufficient privilege
# 5 - program is not installed
# 6 - program is not configured
# 7 - program is not running
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=registercloudguest
EXEC=/usr/sbin/registercloudguest

. /etc/rc.status
rc_reset

# Exit if the package is not installed
[ -x "$EXEC" ] || exit 0


case "$1" in
    start)
        $EXEC
        rc_status -v
        ;;
    stop)
        rc_status -v
        ;;
    reload)
        $EXEC
        rc_status -v
        ;;
    restart|force-reload)
        $EXEC
        rc_status -v
        ;;
    *)
        echo $"Usage: $0 {start|stop|reload|restart|force-reload}"
    exit 3
    ;;
esac
